// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxcrfhnhaigzmxlkssct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4Y3JmaG5oYWlnem14bGtzc2N0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMDE0OTYsImV4cCI6MjA3Mjg3NzQ5Nn0.iHtBhCC1eyHMe3RAHZt5_gtgJx96pVvZ0XksjUJLZdU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});